# Generated by Django 5.0.4 on 2024-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALERIA', 'Galeria'), ('CORTES', 'Cortes')], default='', max_length=100),
        ),
    ]
