# Generated by Django 5.0.4 on 2024-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0004_fotografia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('BARBEARIA', 'Barbearia'), ('CORTES', 'Cortes')], default='BARBEARIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='assets/'),
        ),
    ]
