# Generated by Django 5.0.4 on 2024-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0007_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Barbearia', 'Barbearia'), ('Cortes', 'Cortes')], default='BARBEARIA', max_length=20),
        ),
    ]
