# Generated by Django 5.0.4 on 2024-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0011_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
