# Generated by Django 5.0.4 on 2024-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_shop', '0013_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('barbearia', 'Barbearia'), ('cortes', 'Cortes')], default='BARBEARIA', max_length=20),
        ),
    ]
